### ISSUE TITLE
Lines are shifted, while using non-native emojis

### ISSUE THREAD

**Issue by rob-heine** [morkro/atom-emoji-syntax#44] opened 2017-02-28 08:31 UTC
Unluckily the lines are completely shifted, while using anything but `native` as Emoji Style.

![image](https://cloud.githubusercontent.com/assets/14014623/23397338/58dce728-fd98-11e6-8e99-4ac70b81c176.png)

Using Atom v1.14.3 (ia32) on MS Windows 10 (Version 1511, Build 10586.753) here.

**Comment by morkro** [comment] 2017-02-28 09:03
Oh, that's a first. Haven't seen that one before. And it only happens once you switch from `native` to a custom style? Do the others look the same or is it only that specific set?

Thanks for reporting! ✌️

**Comment by rob-heine** [comment] 2017-02-28 09:07
The problem looks similar on other emoji (not-native) styles, too. Switching to `Noto Emoji` gives the following formatting:

![image](https://cloud.githubusercontent.com/assets/14014623/23398638/9eacf590-fd9d-11e6-8614-2840c308a3f0.png)

**Comment by morkro** [comment] 2017-02-28 09:13
Ah shit, sorry for that! I use a `Twemoji` all the time, but on macOS and haven't encountered that. Will look into that later today when I have Windows available :)

**Comment by rob-heine** [comment] 2017-03-01 13:38
Problem persists in atom `v1.14.4`.

**Comment by morkro** [comment] 2017-03-01 20:46
I have figured out what the problem is. On Windows `vertical-align: middle;` _[(which I apply to the emoji)](https://github.com/morkro/atom-emoji-syntax/blob/master/lib/stylesheet.js#L18)_ causes lines to break if the `line-height` is below `1.2`. It works without issues on macOS. 

Will publish a fix for this very soon :)

**Comment by morkro** [comment] 2017-03-01 21:00
Hey @rob-heine, I think I fixed the line-height related issue. Can you please update the package to the latest release and check? :)

**Comment by rob-heine** [comment] 2017-03-02 08:25
@morkro `v1.6.5` lgtm :+1:

![image](https://cloud.githubusercontent.com/assets/14014623/23498920/2c52a4b6-ff2a-11e6-8b0c-5762d2035224.png)

**Comment by morkro** [comment] 2017-03-02 09:55
That makes me happy! 👍

**Closed by morkro** 2017-03-02 09:55 UTC
Labels: bug
